# Generated by Django 4.1.7 on 2023-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FacultyID', models.IntegerField(primary_key=True, serialize=False)),
                ('Prefix', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('ResearchArea', models.CharField(max_length=255)),
            ],
        ),
    ]
