# Generated by Django 4.1.7 on 2023-08-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_dsata_delete_student_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20, unique=True)),
                ('sfname', models.TextField(max_length=30)),
                ('gender', models.TextField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=50)),
                ('mob', models.IntegerField()),
                ('section', models.CharField(default='NA', max_length=1)),
                ('degree', models.TextField(default='NA', max_length=30)),
                ('year', models.IntegerField(default=1)),
                ('semester', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_dsata',
        ),
    ]
