# Generated by Django 4.1.7 on 2023-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_student_data_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='mob',
            field=models.BigIntegerField(),
        ),
    ]
