# Generated by Django 4.1.7 on 2023-09-20 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 22, 14, 29, 618230)),
        ),
    ]
