# Generated by Django 4.1.7 on 2023-12-01 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_course_alter_announcement_time_alter_chats_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 23, 32, 46, 872603)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 23, 32, 46, 871610)),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student_data')),
            ],
        ),
    ]
