# Generated by Django 4.1.7 on 2023-12-02 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_alter_announcement_time_alter_chats_time_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 11, 49, 23, 133091)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 11, 49, 23, 132412)),
        ),
    ]
