# Generated by Django 4.1.7 on 2023-12-08 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_hostel_alter_announcement_time_alter_chats_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='hostelname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 10, 9, 43, 252008)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 10, 9, 43, 251011)),
        ),
    ]
