# Generated by Django 4.1.7 on 2023-12-08 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_rename_hostelname_hostel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30)),
                ('ta', models.IntegerField()),
                ('mst1', models.IntegerField()),
                ('mst2', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 10, 12, 10, 589936)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 10, 12, 10, 589635)),
        ),
    ]
