# Generated by Django 4.2 on 2024-03-08 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_marks_alter_announcement_time_alter_chats_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 17, 26, 42, 935832)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 17, 26, 42, 935832)),
        ),
    ]
